unwanted_words_in_name = [
    'Şok Market',
    'A101',
    'Bim',
    'Migros',
    'Carrefour',
    'Tarım Kredi Kooperatifleri',
    'Koçtaş',
    'Tekzen',
    'Çağrı Market',
    'A101 Market',
    'File Market',
    'File',
    'Migros Sanal Market',
    'Migros Market',
    'Migros Jet',
    'Yemeksepeti',
    'Yemek Sepeti',
    'TK Kooperatifleri',
    'TK Koop',
    'TK Koop.',
    'TK Koop. A.Ş.',
    'Ekomini',
    'Ekomini Market',
    'Seç Market',
    'Seç Marketler',
    'Seç Marketleri',
    '101',
    '101 Market',
    'BİM'
]